spring:
  datasource:
    url: jdbc:mysql://growpalettedb.cfu840og0gs2.ap-northeast-2.rds.amazonaws.com
    username: root
    password: growpalette
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000